"""Initial migration from Prisma schema

Revision ID: 4663838dbf23
Revises: 
Create Date: 2025-09-14 16:54:51.500891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4663838dbf23'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_prisma_migrations')
    op.alter_column('conversations', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('conversations', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('conversations', 'group_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('conversations', 'sender',
               existing_type=sa.TEXT(),
               type_=sa.Enum('USER', 'AI', name='messagesender'),
               existing_nullable=False)
    op.alter_column('conversations', 'messageType',
               existing_type=sa.TEXT(),
               type_=sa.Enum('TEXT', 'IMAGE', 'DOCUMENT', 'AUDIO', 'SYSTEM', name='messagetype'),
               existing_nullable=False,
               existing_server_default=sa.text("'TEXT'"))
    op.alter_column('conversations', 'platform',
               existing_type=sa.TEXT(),
               type_=sa.Enum('WHATSAPP', 'TELEGRAM', 'API', name='platform'),
               existing_nullable=True)
    op.drop_index(op.f('conversations_group_id_timestamp_idx'), table_name='conversations')
    op.drop_index(op.f('conversations_platform_timestamp_idx'), table_name='conversations')
    op.drop_index(op.f('conversations_user_id_timestamp_idx'), table_name='conversations')
    op.create_index('idx_group_timestamp', 'conversations', ['group_id', 'timestamp'], unique=False)
    op.create_index('idx_platform_timestamp', 'conversations', ['platform', 'timestamp'], unique=False)
    op.create_index('idx_user_timestamp', 'conversations', ['user_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_conversations_group_id'), 'conversations', ['group_id'], unique=False)
    op.create_index(op.f('ix_conversations_timestamp'), 'conversations', ['timestamp'], unique=False)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.create_foreign_key(None, 'conversations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'conversations', 'groups', ['group_id'], ['id'], ondelete='CASCADE')
    op.alter_column('group_members', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('group_members', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('group_members', 'group_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('group_members', 'role',
               existing_type=sa.TEXT(),
               type_=sa.Enum('ADMIN', 'MEMBER', name='grouprole'),
               existing_nullable=False,
               existing_server_default=sa.text("'MEMBER'"))
    op.drop_index(op.f('group_members_user_id_group_id_key'), table_name='group_members')
    op.create_unique_constraint('unique_user_group_membership', 'group_members', ['user_id', 'group_id'])
    op.drop_constraint(None, 'group_members', type_='foreignkey')
    op.drop_constraint(None, 'group_members', type_='foreignkey')
    op.create_foreign_key(None, 'group_members', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'group_members', 'groups', ['group_id'], ['id'], ondelete='CASCADE')
    op.alter_column('groups', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('groups', 'whatsapp_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('groups', 'telegram_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('groups', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('groups', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('groups_telegram_id_key'), table_name='groups')
    op.drop_index(op.f('groups_whatsapp_id_key'), table_name='groups')
    op.create_index(op.f('ix_groups_telegram_id'), 'groups', ['telegram_id'], unique=True)
    op.create_index(op.f('ix_groups_whatsapp_id'), 'groups', ['whatsapp_id'], unique=True)
    op.alter_column('users', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'whatsapp_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'telegram_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'api_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('users_api_id_key'), table_name='users')
    op.drop_index(op.f('users_telegram_id_key'), table_name='users')
    op.drop_index(op.f('users_whatsapp_id_key'), table_name='users')
    op.create_index(op.f('ix_users_api_id'), 'users', ['api_id'], unique=True)
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_index(op.f('ix_users_whatsapp_id'), 'users', ['whatsapp_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_whatsapp_id'), table_name='users')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_index(op.f('ix_users_api_id'), table_name='users')
    op.create_index(op.f('users_whatsapp_id_key'), 'users', ['whatsapp_id'], unique=1)
    op.create_index(op.f('users_telegram_id_key'), 'users', ['telegram_id'], unique=1)
    op.create_index(op.f('users_api_id_key'), 'users', ['api_id'], unique=1)
    op.alter_column('users', 'api_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'telegram_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'whatsapp_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_groups_whatsapp_id'), table_name='groups')
    op.drop_index(op.f('ix_groups_telegram_id'), table_name='groups')
    op.create_index(op.f('groups_whatsapp_id_key'), 'groups', ['whatsapp_id'], unique=1)
    op.create_index(op.f('groups_telegram_id_key'), 'groups', ['telegram_id'], unique=1)
    op.alter_column('groups', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('groups', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('groups', 'telegram_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('groups', 'whatsapp_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('groups', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'group_members', type_='foreignkey')
    op.drop_constraint(None, 'group_members', type_='foreignkey')
    op.create_foreign_key(None, 'group_members', 'groups', ['group_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'group_members', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('unique_user_group_membership', 'group_members', type_='unique')
    op.create_index(op.f('group_members_user_id_group_id_key'), 'group_members', ['user_id', 'group_id'], unique=1)
    op.alter_column('group_members', 'role',
               existing_type=sa.Enum('ADMIN', 'MEMBER', name='grouprole'),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'MEMBER'"))
    op.alter_column('group_members', 'group_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('group_members', 'user_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('group_members', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.create_foreign_key(None, 'conversations', 'groups', ['group_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'conversations', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_timestamp'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_group_id'), table_name='conversations')
    op.drop_index('idx_user_timestamp', table_name='conversations')
    op.drop_index('idx_platform_timestamp', table_name='conversations')
    op.drop_index('idx_group_timestamp', table_name='conversations')
    op.create_index(op.f('conversations_user_id_timestamp_idx'), 'conversations', ['user_id', 'timestamp'], unique=False)
    op.create_index(op.f('conversations_platform_timestamp_idx'), 'conversations', ['platform', 'timestamp'], unique=False)
    op.create_index(op.f('conversations_group_id_timestamp_idx'), 'conversations', ['group_id', 'timestamp'], unique=False)
    op.alter_column('conversations', 'platform',
               existing_type=sa.Enum('WHATSAPP', 'TELEGRAM', 'API', name='platform'),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('conversations', 'messageType',
               existing_type=sa.Enum('TEXT', 'IMAGE', 'DOCUMENT', 'AUDIO', 'SYSTEM', name='messagetype'),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'TEXT'"))
    op.alter_column('conversations', 'sender',
               existing_type=sa.Enum('USER', 'AI', name='messagesender'),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('conversations', 'group_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('conversations', 'user_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('conversations', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_table('_prisma_migrations',
    sa.Column('id', sa.TEXT(), nullable=False),
    sa.Column('checksum', sa.TEXT(), nullable=False),
    sa.Column('finished_at', sa.DATETIME(), nullable=True),
    sa.Column('migration_name', sa.TEXT(), nullable=False),
    sa.Column('logs', sa.TEXT(), nullable=True),
    sa.Column('rolled_back_at', sa.DATETIME(), nullable=True),
    sa.Column('started_at', sa.DATETIME(), server_default=sa.text('(current_timestamp)'), nullable=False),
    sa.Column('applied_steps_count', sa.INTEGER(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
